language: php

php:
    - "7.2"
    - "7.3"
    - hhvm
    - nightly

sudo: false

git:
    submodules: false

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

# addons:
#     sonarcloud:
#         organization: "canax"

before_script:
    - make install

script:
    - make check
    - make test
    #- sonar-scanner
